[project]
name = ""
version = ""
description = ""
authors = [
    {name = "kwseeker", email = "xiaohuileee@gmail.com"},
]
dependencies = [
    "SpeechRecognition>=3.10.0",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

